{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-sentry.serviceAccountName" . }}
  namespace: {{ include "k8s-sentry.namespace" . }}
  labels:
    {{- include "k8s-sentry.labels" . | nindent 4 }}
{{- end }}
